development:
  adapter: postgresql
  database: escola_das_pleiades_development
  username: andre
  password: andre
  host: localhost
  poor: 5

test:
  adapter: postgresql
  database: escola_das_pleiades_test
  username: andre
  password: andre
  host: localhost
  poor: 5

production:
  adapter: postgresql
  database: escola_das_pleiades_production
  host: localhost
  poor: 5
