development:
  adapter: postgresql
  database: escola_das_pleiades_development
  username: postgres
  password: postgres
  host: localhost
  poor: 5

test:
  adapter: postgresql
  database: escola_das_pleiades_test
  username: postgres
  password: postgres
  host: localhost
  poor: 5

production:
  adapter: postgresql
  database: escola_das_pleiades_production
  host: localhost
  poor: 5